---
version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    null_handler:
        class: logging.NullHandler
        level: DEBUG

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: WARNING
        formatter: simple
        filename: warning.log
        when: midnight
        backupCount: 30
        encoding: utf8

loggers:
    dev:
        level: DEBUG
        handlers: [console]
        propagate: no

    unibot_status:
        level: INFO
        handlers: [info_file_handler, warning_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [null_handler]
...
